---
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
  vars:
    domain: fabric-ipfs.com
    root_peer_ip_external: 192.168.77.25 # an externaly avaliable ip of root peer, needed for frontend stuff
    kafka_orderer: true  # Enable kafka orderer, we'll have 4 brokers and 3 zookeepers.
    orderer_count: 4 # Amount of orderers in network, assumed that it equals to amount of organization, so each org will have an own orderer copy
    kafka_replicas: 2 # Set kafka_replicas parameter
    kafka_replication_factor: 3 # Set kafka_replication_factor parameter (https://hyperledger-fabric.readthedocs.io/en/release-1.2/kafka.html)
  children:
    nodes:
      hosts:
        mainorg.fabric-ipfs.com: # Describes which containers will run on this node
          node_roles:
            - root_orderer # This node will be used to generate crypto-config for other orderers
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - root_peer # This node will be used to create channels and instantiate chaincode
            - zookeeper # Hosts zookeeper container for kafka-cluster
            - kafka_broker # Hosts broker container for kafka-cluster
          org: mainorg # Organization name
          zookeeper_id: 0 # ID for zookeeper
          orderer_id: 0
          kafka_broker_id: 0 # ID for kafka-broker
          ansible_host: 192.168.77.25 # Real ip address or domain name of the machine
          ansible_user: ubuntu  # User with sudo access
          ansible_ssh_port: 22 # Specify ssh-port here, if case of it's not defaulted.
        # Same structure for any other nodes
        privated.fabric-ipfs.com:
          node_roles:
            - orderer # This node will host an orderer-service
            - peer # This node will host peers and api containers for organization
            - zookeeper # Hosts zookeeper container for kafka-cluster
            - kafka_broker # Hosts broker container for kafka-cluster
          org: privated
          orderer_id: 1 # ID of orderer-service which is running on this host
          zookeeper_id: 1
          kafka_broker_id: 1
          ansible_host: 192.168.78.187
          ansible_user: ubuntu
          ansible_ssh_port: 22
        clienta.fabric-ipfs.com:
          node_roles:
            - orderer
            - peer
            - zookeeper
            - kafka_broker
          org: clienta
          orderer_id: 2
          zookeeper_id: 2
          kafka_broker_id: 2
          ansible_host: 192.168.77.17
          ansible_user: ubuntu
          ansible_ssh_port: 22
        clientb.fabric-ipfs.com: # This node will host only kafka-broker and peer.
          node_roles:
            - peer
            - orderer
            - kafka_broker
          org: clientb
          orderer_id: 3
          kafka_broker_id: 3
          ansible_host: 192.168.78.182
          ansible_user: ubuntu
          ansible_ssh_port: 22
