version: '2'

services:
  zookeeper.{{ inventory_hostname }}:
    container_name: zookeeper.{{ inventory_hostname }}
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID={{ zookeeper_id }}
      - ZOO_SERVERS={% for fabric_host in groups['nodes'] %}{% if 'zookeeper' in hostvars[fabric_host].node_roles %}server.{{hostvars[fabric_host].zookeeper_id}}=zookeeper.{{ hostvars[fabric_host].inventory_hostname }}:{{ zookeper_ports[1] }}:{{ zookeper_ports[2] }} {% endif %}{% endfor %}

    ports:
      - {{ zookeper_ports[0] }}:2181
      - {{ zookeper_ports[1] }}:2888
      - {{ zookeper_ports[2] }}:3888
    extra_hosts:
{% for fabric_host in groups['nodes'] %}
{% if 'zookeeper' in hostvars[fabric_host].node_roles %}
{% if hostvars[fabric_host].inventory_hostname|string() != inventory_hostname|string() %}
      - zookeeper.{{ hostvars[fabric_host].inventory_hostname }}:{{ hostvars[fabric_host].ansible_host }}
{% endif %}
{% endif %}
{% endfor %}